# Site settings
title: Electric Sauna
header-img: img/home-bg.png
email: robin.pahlman@gmail.com
copyright_name: aut0maat10
description: > # this means to ignore newlines until "baseurl:"
  It's About Code!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: robinpahlman
github_username:  aut0maat10
learn_profile: aut0maat10
email_username: robin.pahlman@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
